### ISSUE TITLE
Event emit on destination before original object?

### ISSUE THREAD

**Issue by marcofanch** [pgte/propagate#5]
Hi, I found this module interesting, which doesn't do actual `.on()` for the propagation, at the end saved many unnecessary listeners.

One question I want to ask is, why the events are emitted from the destination object before the original?

Under the concept of "propagation", the event should be emitted one after another, started from the source.

Did I misunderstand the concept or your implementation?

**Comment by pgte** [comment]
Propagate emits on the destination before emitting on the source.
This behavior works for the use cases I was using this for.

(If you need to change this or make this optional, I can take a look at a PR.)

**Comment by marcofanch** [comment]
A very simple change, just reverse the invocation order.
This is more intuitive because if the source didn't emit, the dest shouldn't emit.

Please see if this still work for your use case.
Thanks.

**Comment by pgte** [comment]
@marcofanch thanks!

Landed on v1.0.0.
